seed: 42  # Reproducibility seed
default_window_size: 6
custom_window_size:
  '29187': 5
  '28434': 5
exclude_deployments:
  - '26982'
  - '15812'
  - '25712'

paths:
  base_directory: 'excel_AIS\\raw_excel_AIS'
  csv_location: 'excel_AIS\\processed_excel_AIS'
  raw_data_folder: 'data'

